/*
* This header is generated by classdump-dyld 0.7
* on Friday, November 7, 2014 at 1:46:44 AM Eastern European Standard Time
* Operating System: Version 8.1 (Build 12B411)
* Image Source: /System/Library/PrivateFrameworks/CommunicationsSetupUI.framework/CommunicationsSetupUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013 by Elias Limneos.
*/


@protocol PSHeaderFooterView
@optional
-(CGFloat)preferredHeightForWidth:(CGFloat)arg1 inTableView:(id)arg2;
-(CGFloat)preferredHeightForWidth:(CGFloat)arg1;

@required
-(id)initWithSpecifier:(id)arg1;

@end

